import type { EducationPlan } from '../../types/plan';

export const fallbackPlans: EducationPlan[] = [
  {
    id: 9001,
    title: 'Веб-технологии',
    faculty: 'ФИТ',
    level: 'Бакалавриат',
    studyForm: 'Очная',
    year: 2025,
    duration: '4 года',
    description:
      'Проектирование современных веб-сервисов, frontend и backend систем, пользовательских интерфейсов и облачных продуктов.',
    totalHours: 7488,
    credits: 208,
    semesters: 8,
    sourceFileName: 'fallback-web-technologies.xlsx',
    code: '09.03.04',
    competencies: [
      { name: 'Математика', value: 62 },
      { name: 'Программирование', value: 94 },
      { name: 'Аналитика', value: 76 },
      { name: 'Soft Skills', value: 68 },
      { name: 'Практика', value: 88 },
    ],
    disciplines: [
      {
        id: 1,
        name: 'Алгоритмы и структуры данных',
        module: 'Базовый',
        semester: 1,
        hours: 144,
        credits: 4,
      },
      {
        id: 2,
        name: 'Frontend-разработка',
        module: 'Профильный',
        semester: 3,
        hours: 180,
        credits: 5,
      },
      {
        id: 3,
        name: 'Backend-разработка',
        module: 'Профильный',
        semester: 4,
        hours: 180,
        credits: 5,
      },
      { id: 4, name: 'Командный проект', module: 'Практика', semester: 6, hours: 216, credits: 6 },
    ],
  },
  {
    id: 9002,
    title: 'Системная аналитика больших данных',
    faculty: 'ФИТ',
    level: 'Магистратура',
    studyForm: 'Очная',
    year: 2025,
    duration: '2 года',
    description:
      'Подготовка аналитиков данных и архитекторов цифровых продуктов: моделирование, BI, ML-пайплайны и исследовательская практика.',
    totalHours: 4320,
    credits: 120,
    semesters: 4,
    sourceFileName: 'fallback-data-analytics.xlsx',
    code: '09.04.03',
    competencies: [
      { name: 'Математика', value: 86 },
      { name: 'Программирование', value: 74 },
      { name: 'Аналитика', value: 96 },
      { name: 'Soft Skills', value: 72 },
      { name: 'Практика', value: 82 },
    ],
    disciplines: [
      {
        id: 5,
        name: 'Математическое моделирование',
        module: 'Базовый',
        semester: 1,
        hours: 180,
        credits: 5,
      },
      {
        id: 6,
        name: 'Инженерия данных',
        module: 'Профильный',
        semester: 2,
        hours: 216,
        credits: 6,
      },
      { id: 7, name: 'BI-системы', module: 'Профильный', semester: 3, hours: 144, credits: 4 },
      {
        id: 8,
        name: 'Научно-исследовательская работа',
        module: 'Практика',
        semester: 4,
        hours: 324,
        credits: 9,
      },
    ],
  },
];
